force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>Certification</label>
    <nameField>
        <displayFormat>CERT-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Certification_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Certification_Assessment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This is the lookup to the Assessment Definition Record.</description>
    <label>Certification Assessment</label>
    <referenceTo>AssessmentDefinition</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Certification_Results__c.field-meta.xml
<CustomField>
    <fullName>Certification_Results__c</fullName>
    <description>Results of the last exam attempt</description>
    <label>Certification Results</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Completion_Status__c.field-meta.xml
<CustomField>
    <fullName>Completion_Status__c</fullName>
    <description>This field tracks the completion of the Certification Exam. Until the Certification Status is not Passed, the Completion status will be Pending</description>
    <label>Completion Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Product related to this certification</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Omnipod 5</fullName>
            </value>
            <value>
                <fullName>DASH</fullName>
            </value>
            <value>
                <fullName>UST400</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Retake_Exam__c.field-meta.xml
<CustomField>
    <fullName>Retake_Exam__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CSM to use this field to enable Trainers to retake the exam</description>
    <label>Retake Exam?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TakeExamCmpController.cls
/**
 * @author      : Rohan Saxena
 * @created Date: 20th Nov 2025
 * @description : This class provide Certification and its related object data.
 */
public without sharing class TakeExamCmpController {
   /**
   * @description Method to get Certification record.
   * @param certificationId Id of Certification.
   *  @return Certification record.
   */
    @AuraEnabled(cacheable=false)
    public static Certification__c getCertification(Id certificationId) {
        List<Certification__c> lstCertification = [
            SELECT Id, Retake_Exam__c, Completion_Status__c, Certification_Results__c, Product__c
            FROM Certification__c
            WHERE Id = :certificationId
            WITH USER_MODE
        ];
        if (!lstCertification.isEmpty()) {
            return lstCertification[0];
        }
        return null;
    }

    /**
   * @description Method to get Certification related omni data.
   * @param certificationId Id of Certification.
   * @return Certification record.
   */
    @AuraEnabled(cacheable=true)
    public static Certification__c getCertificationRelatedOmniscript(Id certificationId) {
        List<Certification__c> lstCertification = [
            SELECT Id,
                   Certification_Assessment__r.OmniProcess.Type,
                   Certification_Assessment__r.OmniProcess.SubType,
                   Certification_Assessment__r.OmniProcess.Language,
                   Certification_Assessment__r.OmniProcess.Name,
                   Certification_Assessment__r.Assessment_Question_Set__c
            FROM Certification__c
            WHERE Id = :certificationId WITH SYSTEM_MODE
        ];
        if (!lstCertification.isEmpty()) {
            return lstCertification[0];
        }
        return null;
    }
}