force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>Certification</label>
    <nameField>
        <displayFormat>CERT-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Certification_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Certification_Assessment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This is the lookup to the Assessment Definition Record.</description>
    <label>Certification Assessment</label>
    <referenceTo>AssessmentDefinition</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Certification_Date__c.field-meta.xml
<CustomField>
    <fullName>Certification_Date__c</fullName>
    <description>Date of the last exam attempt</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Certification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Certification_Results__c.field-meta.xml
<CustomField>
    <fullName>Certification_Results__c</fullName>
    <description>Results of the last exam attempt</description>
    <label>Certification Results</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Completion_Status__c.field-meta.xml
<CustomField>
    <fullName>Completion_Status__c</fullName>
    <description>This field tracks the completion of the Certification Exam. Until the Certification Status is not Passed, the Completion status will be Pending</description>
    <label>Completion Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Product related to this certification</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Omnipod 5</fullName>
            </value>
            <value>
                <fullName>DASH</fullName>
            </value>
            <value>
                <fullName>UST400</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Retake_Exam__c.field-meta.xml
<CustomField>
    <fullName>Retake_Exam__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CSM to use this field to enable Trainers to retake the exam</description>
    <label>Retake Exam?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Trainer_Name__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Name__c</fullName>
    <description>This field is a master detail to the account.</description>
    <label>Trainer Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Trainer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Multi_Location_Contract__c/Multi_Location_Contract__c.object-meta.xml
<CustomObject>
    <description>This object is a junction between Contract and Account, enabling a Contract to be linked to multiple practices.</description>
    <label>Multi Location Contract</label>
    <nameField>
        <displayFormat>MLC-{00000}</displayFormat>
        <label>Multi Location Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Multi Location Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Multi_Location_Contract__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>References the actual Contract to which one or more Practices are related to.</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Multi Location Contracts</relationshipLabel>
    <relationshipName>Multi_Location_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Multi_Location_Contract__c/fields/Related_Location__c.field-meta.xml
<CustomField>
    <fullName>Related_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>References the Practice associated with the primary Contract.</description>
    <label>Related Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Practice</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Multi Location Contracts</relationshipLabel>
    <relationshipName>Multi_Location_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>TRN-{0000}</displayFormat>
        <label>Training Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Educator_Type__c.field-meta.xml
<CustomField>
    <fullName>Educator_Type__c</fullName>
    <description>Defines the training format and/or the educator that will deliver the training</description>
    <label>Educator Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPT</fullName>
            </value>
            <value>
                <fullName>OT</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
            </value>
            <value>
                <fullName>ST</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>CTS</fullName>
            </value>
            <value>
                <fullName>OH</fullName>
                <isActive>false</isActive>
                <label>OH</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/External_Trainer__c.field-meta.xml
<CustomField>
    <fullName>External_Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Trainer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Trainer</value>
        </filterItems>
        <filterItems>
            <field>Account.Do_Not_Use_For_Training__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trainings (External Trainer)</relationshipLabel>
    <relationshipName>Trainings3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TrainingController_Test.cls
/**
 * @description Unit tests for TrainingController
 * Covers positive/negative/bulk paths for all public methods.
 * Requirements:
 * - No SeeAllData
 * - startTest/stopTest usage
 * - Meaningful assertions
 * - @TestSetup for test data
 */
@IsTest
private class TrainingController_Test {
  /**
   * @description : Method to Create Test Data
   */
  @testSetup
  static void createData() {
    insert TestDataFactory.getAccountofTrainerRecordType(
      new Map<String, Object>()
    );
    Account trainer = [SELECT id, PersonContactId FROM Account];
    trainer.Contract_Type__c = 'Level 2';
    update trainer;

    Account practice = TestDataFactory.getAccountofPracticeRecordType();
    insert practice;

    AccountContactRelation acr = new AccountContactRelation();
    acr.ContactId = trainer.PersonContactId;
    acr.AccountId = practice.Id;
    acr.Roles = ConstantsUtil.ACR_ROLE_TRAINER;
    insert acr;

    AssessmentQuestionSet testQuestionSet = TestDataFactory.getAssessmentQuestionSet();
    insert testQuestionSet;

    OmniProcess testOmni = TestDataFactory.getOmniProcess(
      new Map<String, Object>{
        'Name' => 'Test OmniScript',
        'Type' => 'Assessment',
        'SubType' => 'Test',
        'Language' => 'English',
        'IsActive' => true,
        'OmniProcessType' => 'OmniScript'
      }
    );
    insert testOmni;

    insert TestDataFactory.getAssessmentDefinition(
      new Map<String, Object>{
        'Assessment_Question_Set__c' => testQuestionSet.Id,
        'OmniProcessId' => testOmni.Id,
        'Test_Name__c' => 'Test Exam',
        'Purpose' => 'Certification'
      }
    );

    AssessmentDefinition ad = [SELECT id FROM AssessmentDefinition LIMIT 1];
    Certification__c c = TestDataFactory.getCertification(
      new Map<String, Object>{
        'Trainer_Name__c' => trainer.Id,
        'Certification_Assessment__c' => ad.Id,
        'Retake_Exam__c' => true,
        'Completion_Status__c' => 'Completed',
        'Certification_Results__c' => 'Passed',
        'Certification_Date__c' => System.Today().addDays(-10),
        'Product__c' => 'Omnipod 5'
      }
    );
    insert c;

    Contract ccContract = TestDataFactory.getContract(trainer.Id);
    ccContract.clinic_admin_email__c = 'a@a.com';
    ccContract.Clinic_Admin_Name__c = 'a';
    ccContract.StartDate = Date.today();
    ccContract.EndDate = Date.today().addDays(100);
    insert ccContract;
    ccContract.Status = 'Activated';
    update ccContract;

    Multi_Location_Contract__c mlc = new Multi_Location_Contract__c();
    mlc.Related_Location__c = practice.Id;
    mlc.Contract__c = ccContract.Id;
    insert mlc;

    Training__c cptTraining;
    Training__c ccTraining;

    cptTraining = new TestDataFactory.CreateTrainingRecord()
      .setRecordType(ConstantsUtil.TRAINING_LIVE_TRAINING_RT)
      .setEducatorType(ConstantsUtil.EDUCATOR_TYPE_CPT)
      .setTrainingStage(ConstantsUtil.STAGE_PENDING_ACCEPTANCE)
      .setAccount(practice.Id)
      .save()
      .getRecord();
    cptTraining.External_Trainer__c = trainer.Id;
    update cptTraining;

    // Another CC training for CC list query path
    ccTraining = new TestDataFactory.CreateTrainingRecord()
      .setRecordType(ConstantsUtil.TRAINING_LIVE_TRAINING_RT)
      .setEducatorType(ConstantsUtil.EDUCATOR_TYPE_CC)
      .setTrainingStage(ConstantsUtil.STAGE_PENDING_ACCEPTANCE)
      .setAccount(practice.Id)
      .save()
      .getRecord();
    ccTraining.External_Trainer__c = trainer.Id;
    update ccTraining;
  }

  /**
   * @description : Method to Test reassignTraining
   */
  @isTest
  static void testReassignTraining() {
    Training__c t = [SELECT id FROM Training__c LIMIT 1];
    Test.startTest();
    TrainingController.reassignTraining(t.id);
    Test.stopTest();
    Training__c t2 = [SELECT id, Training_Stage__c FROM Training__c LIMIT 1];
    Assert.areEqual(
      t2.Training_Stage__c,
      ConstantsUtil.STAGE_PENDING_ACCEPTANCE,
      'Training is Re Assigned and Stage updated to PENDING_ACCEPTANCE'
    );
  }

  /**
   * @description : Method to Test Exception handling of reassignTraining
   */
  @isTest
  static void testReassignTrainingException() {
    Test.startTest();
    try {
      TrainingController.reassignTraining(null);
    } catch (Exception e) {
      Assert.isNotNull(e, 'Exception is Thrown');
    }
    Test.stopTest();
  }
  /**
   * @description : Method to Test UpdateTrainingStage
   */
  @isTest
  static void testUpdateTrainingStage() {
    Training__c t = [SELECT id FROM Training__c LIMIT 1];
    Test.startTest();
    try {
      TrainingController.updateTrainingStage(t.id, false);
      TrainingController.updateTrainingStage('', false);
    } catch (Exception e) {
      Assert.isNotNull(e, 'Exception is Thrown');
    }
    Test.stopTest();
  }
  /**
   * @description : Method to Test UpdateTrainingStage when called from a Quick Action
   */

  @isTest
  static void testUpdateTrainingStageFromQuickAction() {
    Training__c t = [SELECT id FROM Training__c LIMIT 1];
    Test.startTest();
    TrainingController.updateTrainingStage(t.id, true);
    Test.stopTest();
    Training__c t2 = [SELECT id, Training_Stage__c FROM Training__c LIMIT 1];
    Assert.areEqual(
      t2.Training_Stage__c,
      ConstantsUtil.STAGE_ACCEPTED,
      'Training is Accepted'
    );
  }

  /**
   * @description : Method to Test UpdateTrainingDeclineData
   */
  @isTest
  static void testUpdateTrainingDeclineData() {
    Training__c t = [SELECT id FROM Training__c LIMIT 1];
    TrainingController.TrainingDeclineWrapper wrap = new TrainingController.TrainingDeclineWrapper();
    wrap.trainingId = t.Id;
    wrap.isClickFromQuickAction = false;
    wrap.declineReason = 'Compatibility/supply issue';
    Test.startTest();
    TrainingController.updateTrainingDeclineData(JSON.serialize(wrap));
    Test.stopTest();
    Training__c t2 = [SELECT id, Training_Stage__c FROM Training__c LIMIT 1];
    Assert.areEqual(
      t2.Training_Stage__c,
      ConstantsUtil.STAGE_DECLINED,
      'Training is Declined'
    );
  }

  /**
   * @description : Method to Test Exception Handling of UpdateTrainingDeclineData
   */
  @isTest
  static void testUpdateTrainingDeclineDataException() {
    TrainingController.TrainingDeclineWrapper wrap = new TrainingController.TrainingDeclineWrapper();
    wrap.trainingId = null;
    wrap.isClickFromQuickAction = true;
    wrap.declineReason = 'Compatibility/supply issue';
    Test.startTest();
    try {
      TrainingController.updateTrainingDeclineData(JSON.serialize(wrap));
    } catch (Exception e) {
      Assert.isNotNull(e, 'Exception is Thrown');
    }
    Test.stopTest();
  }

  /**
   * @description : Method to Test LoadData
   */
  @isTest
  static void testLoadData() {
    Account trainer = [
      SELECT id, PersonContactId
      FROM Account
      WHERE PersonContactId != NULL
      LIMIT 1
    ];
    Test.startTest();
    TrainingController.TrainerWrapper wrap = TrainingController.loadData(
      trainer.PersonContactId
    );
    Test.stopTest();
    Assert.areEqual(
      wrap.isPractice,
      false,
      'Practice do not have more than one Trainer'
    );
  }

  /**
   * @description : Method to Test GetTrainingDetails
   */
  @isTest
  static void testGetTrainingDetails() {
    Account trainer = [
      SELECT id, PersonContactId, Trainer_Type__c
      FROM Account
      WHERE PersonContactId != NULL
      LIMIT 1
    ];
    Training__c t = [SELECT id FROM Training__c LIMIT 1];
    Test.startTest();
    TrainingController.TrainerWrapper wrap = TrainingController.getTrainingDetails(
      trainer.PersonContactId,
      t.Id
    );
    Test.stopTest();
    Assert.areEqual(
      wrap.training.Id,
      t.Id,
      'There is only one training assigned to trainer'
    );
  }

  /**
   * @description : Method to Test GetCPTTrainings
   */
  @isTest
  static void testGetCPTTrainings() {
    Account trainer = [
      SELECT id, PersonContactId
      FROM Account
      WHERE PersonContactId != NULL
      LIMIT 1
    ];
    Training__c t = [SELECT id FROM Training__c LIMIT 1];
    t.Educator_Type__c = ConstantsUtil.EDUCATOR_TYPE_CPT;
    t.Training_Stage__c = ConstantsUtil.STAGE_PENDING_ACCEPTANCE;
    update t;
    Test.startTest();
    List<Training__c> trainingList = TrainingController.getCPTTrainings(
      trainer.PersonContactId
    );
    Test.stopTest();
    Assert.areEqual(trainingList.size(), 0, 'No Records Returned');
  }

  /**
   * @description : Method to Test GetCCTrainings
   */
  @isTest
  static void testGetCCTrainings() {
    Account practice = [
      SELECT id, PersonContactId
      FROM Account
      WHERE PersonContactId = NULL
      LIMIT 1
    ];
    Training__c t = [SELECT id FROM Training__c LIMIT 1];
    t.Educator_Type__c = ConstantsUtil.EDUCATOR_TYPE_CC;
    t.Training_Stage__c = ConstantsUtil.STAGE_PENDING_ACCEPTANCE;
    update t;
    Test.startTest();
    List<Training__c> trainingList = TrainingController.getCCTrainings(
      practice.Id
    );
    Test.stopTest();
    Assert.areEqual(trainingList.size(), 0, 'No Records Returned');
  }

  /**
   * @description : Method to Test Exception Handling of Null Input for  loadData , getCCTrainings , getCPTTrainings , getTrainingDetails
   */
  @isTest
  static void testExceptionHandling() {
    try {
      TrainingController.loadData(null);
    } catch (Exception e) {
      Assert.isNotNull(e, 'Exception is Thrown');
    }
    try {
      TrainingController.getCCTrainings(null);
    } catch (Exception e) {
      Assert.isNotNull(e, 'Exception is Thrown');
    }
    try {
      TrainingController.getCPTTrainings(null);
    } catch (Exception e) {
      Assert.isNotNull(e, 'Exception is Thrown');
    }
    try {
      TrainingController.getTrainingDetails(null, null);
    } catch (Exception e) {
      Assert.isNotNull(e, 'Exception is Thrown');
    }
  }
}