force-app/main/default/objects/OrgSync_Training_Staging__c/OrgSync_Training_Staging__c.object-meta.xml
<CustomObject>
    <label>Training Staging</label>
    <nameField>
        <displayFormat>TRNST-{0000}</displayFormat>
        <label>OrgSync Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Stagings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgSync_Training_Staging__c/fields/OrgSync_Account__c.field-meta.xml
<CustomField>
    <fullName>OrgSync_Account__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Training Stagings</relationshipLabel>
    <relationshipName>Training_Stagings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OrgSync_TrainingStagingTriggerTest.cls
/**
 * @description Test class for OrgSync_TrainingStagingTrigger.
 *              Extends the standard TriggerHandler framework.
 * Created Date : Feb 16, 2026
 * Created By   : Neeraj Kumar
 * =========================== Logs ======================================
 * Version      Modified Date       Modified By             Brief Note
 * V1.0.0       Feb 16, 2026        Neeraj Kumar            Initial Version
 */
@IsTest
private class OrgSync_TrainingStagingTriggerTest {

    @IsTest
    static void testInsertAndUpdate() {
        OrgSync_Training_Staging__c staging = new OrgSync_Training_Staging__c();
        String extId = OrgSync_UtilityService.generateUniqueExtId('DELSUC');
        Account acc = new Account(
            LastName = 'To Delete',
            RecordTypeId = ConstantsUtil.ACCOUNT_PATIENT_RT,
            XCDC_ExternalId__c = extId,
            BillingPostalCode = '89765'
        );
        insert acc;
        staging.OrgSync_Account__c = acc.Id;
        Test.startTest();
        insert staging;
        Test.stopTest();

        System.assertNotEquals(null, staging.Id, 'Record should be inserted.');
    }
}