force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>TRN-{0000}</displayFormat>
        <label>Training Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/CSM__c.field-meta.xml
<CustomField>
    <fullName>CSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>User Record of the CSM assigned to territory of the Customer</inlineHelpText>
    <label>CSM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Educator_Type__c.field-meta.xml
<CustomField>
    <fullName>Educator_Type__c</fullName>
    <description>Defines the training format and/or the educator that will deliver the training</description>
    <label>Educator Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPT</fullName>
            </value>
            <value>
                <fullName>OT</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
            </value>
            <value>
                <fullName>ST</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>CTS</fullName>
            </value>
            <value>
                <fullName>OH</fullName>
                <isActive>false</isActive>
                <label>OH</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/Internal_Trainer__c.field-meta.xml
<CustomField>
    <fullName>Internal_Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to an internal trainer user like CSM, TM.</description>
    <label>Internal Trainer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Internal_Trainers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Training_Conducted_Date__c.field-meta.xml
<CustomField>
    <fullName>Training_Conducted_Date__c</fullName>
    <description>The date on which saline or insulin therapy was initiated for the patient.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Training Conducted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TrainingTaskCreationHandler.cls
/**
 * @author      : Bhavya Chanan
 * @created Date: 5th Jan 2026
 * @description : Handler Class to Create Training Activities Tasks
 * ============================ Logs =============================================
 * Version      Modified Date       Modified By                   Brief Note
 * V1.0.0       12th Jan 2026       Bhavya Chanan                 Initial Version NGOMCT-583
 * V1.0.1       23rd Jan 2026       Bhavya Chanan                 NGOMCT-1213
 */
public inherited sharing class TrainingTaskCreationHandler 
{
    public static final String FORCE_EXCEPTION= 'FORCE_EXCEPTION';
    
    /**
    * @description Create Training Activities tasks
    * @param newTrainings The param context containing newTraining records
    * @param oldTrainings The param containing oldTraining records
    */
    public static void createTasks(
        Map<Id, Training__c> newTrainings,
        Map<Id, Training__c> oldTrainings
    ) 
    {
        try
        {
            Map<Id, Id> accountToContactMap = getAccountToPersonContactMap(newTrainings.values());              
            Id taskRecordTypeId = getTaskRecordTypeId(ConstantsUtil.TASK_TRAINING_ACTIVITIES_RT);
        	if (taskRecordTypeId == null) {
                return;
            }
            
        	List<Task> tasksToInsert = new List<Task>();
            for (Training__c trainingRec : newTrainings.values()) {
                
            Training__c oldRec = oldTrainings != null ? oldTrainings.get(trainingRec.Id) : null;
                
            Id contactId = accountToContactMap.get(trainingRec.Account__c);
         
            Boolean validType = trainingRec.Educator_Type__c == ConstantsUtil.EDUCATOR_TYPE_IT || trainingRec.Educator_Type__c == ConstantsUtil.EDUCATOR_TYPE_CTS;

            Boolean trainingConductedDatePresent = trainingRec.Training_Conducted_Date__c != null;

            Boolean trainingConductedDateJustSet = oldRec == null || oldRec.Training_Conducted_Date__c == null;                  
            if (validType && trainingConductedDatePresent && trainingConductedDateJustSet) {                
                     
                Task task = new Task();
                task.Subject = ConstantsUtil.TASK_SUBJECT_PATIENT_7_DAY_FOLLOWUP;
                task.ActivityDate = trainingRec.Training_Conducted_Date__c.addDays(7);
                task.WhatId = trainingRec.Id;
                task.WhoId = contactId;
                task.RecordTypeId = taskRecordTypeId;

                // Owner assignment
                if (trainingRec.Educator_Type__c == ConstantsUtil.EDUCATOR_TYPE_IT) {
                    task.OwnerId = trainingRec.CSM__c;
                } else if (trainingRec.Educator_Type__c == ConstantsUtil.EDUCATOR_TYPE_CTS) {
                    task.OwnerId = trainingRec.Internal_Trainer__c;
                }
                

                if (task.OwnerId != null) {
                    
                    tasksToInsert.add(task);
                }
            }
        }

        if (!tasksToInsert.isEmpty()) {
            Database.insert(
                tasksToInsert,
                false,
                AccessLevel.SYSTEM_MODE
            );            
          
        }
                            
        }
        
        catch (Exception ex) {
            Logger.error('TrainingTaskCreationHandler.createTasks', ex);
            Logger.saveLog();
            
        }                
    }
    
    
    /**
    * @description Returns Dynamic Task Record Type lookup
    * @param recordTypeName The param containing recordypeName
    * @return Id is returned
    */
    public static Id getTaskRecordTypeId(String recordTypeName) {
        try{
            if (Test.isRunningTest() && recordTypeName == FORCE_EXCEPTION) {
            throw new IllegalArgumentException('Forced for test');
            }
            Map<String, Schema.RecordTypeInfo> recordtypeMap =
            Schema.SObjectType.Task.getRecordTypeInfosByName();

        return recordtypeMap.containsKey(recordTypeName)
            ? recordtypeMap.get(recordTypeName).getRecordTypeId()
            : null;
            
        }
        
        catch (Exception ex) {
            Logger.error('TrainingTaskCreationHandler.getTaskRecordTypeId', ex);
            Logger.saveLog();
            return null;
        }        
    }
    
    /**
    * @description Returns a map of AccountId -> PersonContactId
    * @param trainings The param containing training records
    * @return Map<Id, Id> is returned
    */
    public static Map<Id, Id> getAccountToPersonContactMap(
        List<Training__c> trainings
    ) {
        Set<Id> accountIds = new Set<Id>();
        try{
            for (Training__c tr : trainings) {
            if (tr.Account__c != null) {
                accountIds.add(tr.Account__c);
            }
        }

        Map<Id, Id> accountToContactMap = new Map<Id, Id>();

        if (accountIds.isEmpty()) {
            return accountToContactMap;
        }

        for (Account acc : [
            SELECT Id, PersonContactId
            FROM Account
            WHERE Id IN :accountIds
            AND PersonContactId != null
            WITH SYSTEM_MODE
        ]) {
            accountToContactMap.put(acc.Id, acc.PersonContactId);
        }

        return accountToContactMap;
            
        }
        
        catch (Exception ex) {
            Logger.error('TrainingTaskCreationHandler.getAccountToPersonContactMap', ex);
            Logger.saveLog();
            return null;
        }                        
    }
}